spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8888
zuul:
  routes:
    provider-route:
      url: http://localhost:9003/
      path: /provider/**
    consumer-route:
      url: http://localhost:9001/
      path: /consumer/**
eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
      defaultZone: http://localhost:8000/eureka/