server:
  port: 8001
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeeAllencn/spring-cloud-config-repo.git     # 配置git仓库的地址
          search-paths: repo1                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: LeeAllencn                                            # git仓库的账号
          password: King.13                                            # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/